Traceback (most recent call last):
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pyleoclim as pyleo
import matplotlib.pyplot as plt
from matplotlib import gridspec
import matplotlib.transforms as transforms
import matplotlib.patches as mpatches
import seaborn as sns
import numpy as np
import ammonyte as amt
import pandas as pd

from tqdm import tqdm
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import ListedColormap
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpyleoclim[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpyleo[39;00m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m gridspec

File [0;32m~/miniconda3/envs/ammonyte/lib/python3.10/site-packages/pyleoclim/__init__.py:13[0m
[1;32m      2[0m [38;5;124;03m"""[39;00m
[1;32m      3[0m [38;5;124;03mCreated on Wed May 11 10:42:34 2016[39;00m
[1;32m      4[0m 
[0;32m   (...)[0m
[1;32m      9[0m 
[1;32m     10[0m [38;5;124;03m"""[39;00m
[1;32m     11[0m [38;5;66;03m#Import pyleoclim modules[39;00m
[0;32m---> 13[0m [38;5;28;01mimport[39;00m [38;5;21;01mpyleoclim[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m [38;5;28;01mas[39;00m [38;5;21;01mutils[39;00m
[1;32m     14[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mcore[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m     16[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m[38;5;21;01m.[39;00m[38;5;21;01mplotting[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m

File [0;32m~/miniconda3/envs/ammonyte/lib/python3.10/site-packages/pyleoclim/utils/__init__.py:17[0m
[1;32m     15[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mcausality[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m     16[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mlipdutils[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m---> 17[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mmapping[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m     18[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mtsutils[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m     19[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mtsmodel[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m

File [0;32m~/miniconda3/envs/ammonyte/lib/python3.10/site-packages/pyleoclim/utils/mapping.py:8[0m
[1;32m      3[0m [38;5;124;03m"""[39;00m
[1;32m      4[0m [38;5;124;03mMapping utilities for geolocated objects, leveraging Cartopy.[39;00m
[1;32m      5[0m [38;5;124;03m"""[39;00m
[1;32m      6[0m __all__ [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mmap[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mcompute_dist[39m[38;5;124m'[39m]
[0;32m----> 8[0m [38;5;28;01mimport[39;00m [38;5;21;01mcartopy[39;00m
[1;32m      9[0m [38;5;28;01mimport[39;00m [38;5;21;01mcartopy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcrs[39;00m [38;5;28;01mas[39;00m [38;5;21;01mccrs[39;00m
[1;32m     10[0m [38;5;28;01mimport[39;00m [38;5;21;01mcartopy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfeature[39;00m [38;5;28;01mas[39;00m [38;5;21;01mcfeature[39;00m

[0;31mModuleNotFoundError[0m: No module named 'cartopy'

